version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7.1
jobs:
  test-3.7.1:
    docker:
      - image: python:3.7.1
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            pip install -r requirements_test.txt
      - run:
          name: Linting
          command: |
            pre-commit install
            pre-commit run --all-files
      - run:
          name: Install coverage and reporter
          command: |
            pip install coverage==4.5.2
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            set -xu
            ./cc-test-reporter before-build
            SITE_PACKAGES_DIR=$(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
            echo "import coverage; coverage.process_startup()" > "${SITE_PACKAGES_DIR}/coverage.pth"
            export COVERAGE_PROCESS_START=.coveragerc
            python3 -m unittest -v
            coverage combine
            coverage xml
            ./cc-test-reporter after-build --exit-code $?
